// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"psa/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthenticator creates a new instance of MockAuthenticator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthenticator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthenticator {
	mock := &MockAuthenticator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthenticator is an autogenerated mock type for the Authenticator type
type MockAuthenticator struct {
	mock.Mock
}

type MockAuthenticator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthenticator) EXPECT() *MockAuthenticator_Expecter {
	return &MockAuthenticator_Expecter{mock: &_m.Mock}
}

// Logout provides a mock function for the type MockAuthenticator
func (_mock *MockAuthenticator) Logout(ctx context.Context, refreshToken string) error {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthenticator_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthenticator_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockAuthenticator_Expecter) Logout(ctx interface{}, refreshToken interface{}) *MockAuthenticator_Logout_Call {
	return &MockAuthenticator_Logout_Call{Call: _e.mock.On("Logout", ctx, refreshToken)}
}

func (_c *MockAuthenticator_Logout_Call) Run(run func(ctx context.Context, refreshToken string)) *MockAuthenticator_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthenticator_Logout_Call) Return(err error) *MockAuthenticator_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthenticator_Logout_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) error) *MockAuthenticator_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshTokens provides a mock function for the type MockAuthenticator
func (_mock *MockAuthenticator) RefreshTokens(ctx context.Context, refreshToken string) (*domain.TokenPair, error) {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshTokens")
	}

	var r0 *domain.TokenPair
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.TokenPair, error)); ok {
		return returnFunc(ctx, refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.TokenPair); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TokenPair)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthenticator_RefreshTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshTokens'
type MockAuthenticator_RefreshTokens_Call struct {
	*mock.Call
}

// RefreshTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockAuthenticator_Expecter) RefreshTokens(ctx interface{}, refreshToken interface{}) *MockAuthenticator_RefreshTokens_Call {
	return &MockAuthenticator_RefreshTokens_Call{Call: _e.mock.On("RefreshTokens", ctx, refreshToken)}
}

func (_c *MockAuthenticator_RefreshTokens_Call) Run(run func(ctx context.Context, refreshToken string)) *MockAuthenticator_RefreshTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthenticator_RefreshTokens_Call) Return(tokenPair *domain.TokenPair, err error) *MockAuthenticator_RefreshTokens_Call {
	_c.Call.Return(tokenPair, err)
	return _c
}

func (_c *MockAuthenticator_RefreshTokens_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) (*domain.TokenPair, error)) *MockAuthenticator_RefreshTokens_Call {
	_c.Call.Return(run)
	return _c
}

// Signin provides a mock function for the type MockAuthenticator
func (_mock *MockAuthenticator) Signin(ctx context.Context, email string, password string) (*domain.TokenPair, error) {
	ret := _mock.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Signin")
	}

	var r0 *domain.TokenPair
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.TokenPair, error)); ok {
		return returnFunc(ctx, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.TokenPair); ok {
		r0 = returnFunc(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TokenPair)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthenticator_Signin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Signin'
type MockAuthenticator_Signin_Call struct {
	*mock.Call
}

// Signin is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockAuthenticator_Expecter) Signin(ctx interface{}, email interface{}, password interface{}) *MockAuthenticator_Signin_Call {
	return &MockAuthenticator_Signin_Call{Call: _e.mock.On("Signin", ctx, email, password)}
}

func (_c *MockAuthenticator_Signin_Call) Run(run func(ctx context.Context, email string, password string)) *MockAuthenticator_Signin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthenticator_Signin_Call) Return(tokenPair *domain.TokenPair, err error) *MockAuthenticator_Signin_Call {
	_c.Call.Return(tokenPair, err)
	return _c
}

func (_c *MockAuthenticator_Signin_Call) RunAndReturn(run func(ctx context.Context, email string, password string) (*domain.TokenPair, error)) *MockAuthenticator_Signin_Call {
	_c.Call.Return(run)
	return _c
}
