// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"psa/internal/domain"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProfessionProvider creates a new instance of MockProfessionProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfessionProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfessionProvider {
	mock := &MockProfessionProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProfessionProvider is an autogenerated mock type for the ProfessionProvider type
type MockProfessionProvider struct {
	mock.Mock
}

type MockProfessionProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProfessionProvider) EXPECT() *MockProfessionProvider_Expecter {
	return &MockProfessionProvider_Expecter{mock: &_m.Mock}
}

// ActiveProfessions provides a mock function for the type MockProfessionProvider
func (_mock *MockProfessionProvider) ActiveProfessions(ctx context.Context) ([]domain.ActiveProfession, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ActiveProfessions")
	}

	var r0 []domain.ActiveProfession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.ActiveProfession, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.ActiveProfession); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ActiveProfession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfessionProvider_ActiveProfessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActiveProfessions'
type MockProfessionProvider_ActiveProfessions_Call struct {
	*mock.Call
}

// ActiveProfessions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProfessionProvider_Expecter) ActiveProfessions(ctx interface{}) *MockProfessionProvider_ActiveProfessions_Call {
	return &MockProfessionProvider_ActiveProfessions_Call{Call: _e.mock.On("ActiveProfessions", ctx)}
}

func (_c *MockProfessionProvider_ActiveProfessions_Call) Run(run func(ctx context.Context)) *MockProfessionProvider_ActiveProfessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProfessionProvider_ActiveProfessions_Call) Return(activeProfessions []domain.ActiveProfession, err error) *MockProfessionProvider_ActiveProfessions_Call {
	_c.Call.Return(activeProfessions, err)
	return _c
}

func (_c *MockProfessionProvider_ActiveProfessions_Call) RunAndReturn(run func(ctx context.Context) ([]domain.ActiveProfession, error)) *MockProfessionProvider_ActiveProfessions_Call {
	_c.Call.Return(run)
	return _c
}

// ProfessionSkills provides a mock function for the type MockProfessionProvider
func (_mock *MockProfessionProvider) ProfessionSkills(ctx context.Context, professionID uuid.UUID) (*domain.ProfessionDetail, error) {
	ret := _mock.Called(ctx, professionID)

	if len(ret) == 0 {
		panic("no return value specified for ProfessionSkills")
	}

	var r0 *domain.ProfessionDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.ProfessionDetail, error)); ok {
		return returnFunc(ctx, professionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.ProfessionDetail); ok {
		r0 = returnFunc(ctx, professionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ProfessionDetail)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, professionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfessionProvider_ProfessionSkills_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProfessionSkills'
type MockProfessionProvider_ProfessionSkills_Call struct {
	*mock.Call
}

// ProfessionSkills is a helper method to define mock.On call
//   - ctx context.Context
//   - professionID uuid.UUID
func (_e *MockProfessionProvider_Expecter) ProfessionSkills(ctx interface{}, professionID interface{}) *MockProfessionProvider_ProfessionSkills_Call {
	return &MockProfessionProvider_ProfessionSkills_Call{Call: _e.mock.On("ProfessionSkills", ctx, professionID)}
}

func (_c *MockProfessionProvider_ProfessionSkills_Call) Run(run func(ctx context.Context, professionID uuid.UUID)) *MockProfessionProvider_ProfessionSkills_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfessionProvider_ProfessionSkills_Call) Return(professionDetail *domain.ProfessionDetail, err error) *MockProfessionProvider_ProfessionSkills_Call {
	_c.Call.Return(professionDetail, err)
	return _c
}

func (_c *MockProfessionProvider_ProfessionSkills_Call) RunAndReturn(run func(ctx context.Context, professionID uuid.UUID) (*domain.ProfessionDetail, error)) *MockProfessionProvider_ProfessionSkills_Call {
	_c.Call.Return(run)
	return _c
}

// ProfessionTrend provides a mock function for the type MockProfessionProvider
func (_mock *MockProfessionProvider) ProfessionTrend(ctx context.Context, professionID uuid.UUID) (*domain.ProfessionTrend, error) {
	ret := _mock.Called(ctx, professionID)

	if len(ret) == 0 {
		panic("no return value specified for ProfessionTrend")
	}

	var r0 *domain.ProfessionTrend
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.ProfessionTrend, error)); ok {
		return returnFunc(ctx, professionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.ProfessionTrend); ok {
		r0 = returnFunc(ctx, professionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ProfessionTrend)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, professionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfessionProvider_ProfessionTrend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProfessionTrend'
type MockProfessionProvider_ProfessionTrend_Call struct {
	*mock.Call
}

// ProfessionTrend is a helper method to define mock.On call
//   - ctx context.Context
//   - professionID uuid.UUID
func (_e *MockProfessionProvider_Expecter) ProfessionTrend(ctx interface{}, professionID interface{}) *MockProfessionProvider_ProfessionTrend_Call {
	return &MockProfessionProvider_ProfessionTrend_Call{Call: _e.mock.On("ProfessionTrend", ctx, professionID)}
}

func (_c *MockProfessionProvider_ProfessionTrend_Call) Run(run func(ctx context.Context, professionID uuid.UUID)) *MockProfessionProvider_ProfessionTrend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfessionProvider_ProfessionTrend_Call) Return(professionTrend *domain.ProfessionTrend, err error) *MockProfessionProvider_ProfessionTrend_Call {
	_c.Call.Return(professionTrend, err)
	return _c
}

func (_c *MockProfessionProvider_ProfessionTrend_Call) RunAndReturn(run func(ctx context.Context, professionID uuid.UUID) (*domain.ProfessionTrend, error)) *MockProfessionProvider_ProfessionTrend_Call {
	_c.Call.Return(run)
	return _c
}
