// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"psa/internal/domain"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTrendProvider creates a new instance of MockTrendProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTrendProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTrendProvider {
	mock := &MockTrendProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTrendProvider is an autogenerated mock type for the TrendProvider type
type MockTrendProvider struct {
	mock.Mock
}

type MockTrendProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTrendProvider) EXPECT() *MockTrendProvider_Expecter {
	return &MockTrendProvider_Expecter{mock: &_m.Mock}
}

// ProfessionTrend provides a mock function for the type MockTrendProvider
func (_mock *MockTrendProvider) ProfessionTrend(ctx context.Context, professionID uuid.UUID) (*domain.ProfessionTrend, error) {
	ret := _mock.Called(ctx, professionID)

	if len(ret) == 0 {
		panic("no return value specified for ProfessionTrend")
	}

	var r0 *domain.ProfessionTrend
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.ProfessionTrend, error)); ok {
		return returnFunc(ctx, professionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.ProfessionTrend); ok {
		r0 = returnFunc(ctx, professionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ProfessionTrend)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, professionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTrendProvider_ProfessionTrend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProfessionTrend'
type MockTrendProvider_ProfessionTrend_Call struct {
	*mock.Call
}

// ProfessionTrend is a helper method to define mock.On call
//   - ctx context.Context
//   - professionID uuid.UUID
func (_e *MockTrendProvider_Expecter) ProfessionTrend(ctx interface{}, professionID interface{}) *MockTrendProvider_ProfessionTrend_Call {
	return &MockTrendProvider_ProfessionTrend_Call{Call: _e.mock.On("ProfessionTrend", ctx, professionID)}
}

func (_c *MockTrendProvider_ProfessionTrend_Call) Run(run func(ctx context.Context, professionID uuid.UUID)) *MockTrendProvider_ProfessionTrend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTrendProvider_ProfessionTrend_Call) Return(professionTrend *domain.ProfessionTrend, err error) *MockTrendProvider_ProfessionTrend_Call {
	_c.Call.Return(professionTrend, err)
	return _c
}

func (_c *MockTrendProvider_ProfessionTrend_Call) RunAndReturn(run func(ctx context.Context, professionID uuid.UUID) (*domain.ProfessionTrend, error)) *MockTrendProvider_ProfessionTrend_Call {
	_c.Call.Return(run)
	return _c
}
