// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"psa/internal/domain"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCacheProvider creates a new instance of MockCacheProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCacheProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCacheProvider {
	mock := &MockCacheProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCacheProvider is an autogenerated mock type for the CacheProvider type
type MockCacheProvider struct {
	mock.Mock
}

type MockCacheProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCacheProvider) EXPECT() *MockCacheProvider_Expecter {
	return &MockCacheProvider_Expecter{mock: &_m.Mock}
}

// GetProfessionData provides a mock function for the type MockCacheProvider
func (_mock *MockCacheProvider) GetProfessionData(ctx context.Context, professionID uuid.UUID) (*domain.ProfessionDetail, error) {
	ret := _mock.Called(ctx, professionID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfessionData")
	}

	var r0 *domain.ProfessionDetail
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.ProfessionDetail, error)); ok {
		return returnFunc(ctx, professionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.ProfessionDetail); ok {
		r0 = returnFunc(ctx, professionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ProfessionDetail)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, professionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCacheProvider_GetProfessionData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfessionData'
type MockCacheProvider_GetProfessionData_Call struct {
	*mock.Call
}

// GetProfessionData is a helper method to define mock.On call
//   - ctx context.Context
//   - professionID uuid.UUID
func (_e *MockCacheProvider_Expecter) GetProfessionData(ctx interface{}, professionID interface{}) *MockCacheProvider_GetProfessionData_Call {
	return &MockCacheProvider_GetProfessionData_Call{Call: _e.mock.On("GetProfessionData", ctx, professionID)}
}

func (_c *MockCacheProvider_GetProfessionData_Call) Run(run func(ctx context.Context, professionID uuid.UUID)) *MockCacheProvider_GetProfessionData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCacheProvider_GetProfessionData_Call) Return(professionDetail *domain.ProfessionDetail, err error) *MockCacheProvider_GetProfessionData_Call {
	_c.Call.Return(professionDetail, err)
	return _c
}

func (_c *MockCacheProvider_GetProfessionData_Call) RunAndReturn(run func(ctx context.Context, professionID uuid.UUID) (*domain.ProfessionDetail, error)) *MockCacheProvider_GetProfessionData_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfessionTrend provides a mock function for the type MockCacheProvider
func (_mock *MockCacheProvider) GetProfessionTrend(ctx context.Context, professionID uuid.UUID) (*domain.ProfessionTrend, error) {
	ret := _mock.Called(ctx, professionID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfessionTrend")
	}

	var r0 *domain.ProfessionTrend
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.ProfessionTrend, error)); ok {
		return returnFunc(ctx, professionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.ProfessionTrend); ok {
		r0 = returnFunc(ctx, professionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ProfessionTrend)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, professionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCacheProvider_GetProfessionTrend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfessionTrend'
type MockCacheProvider_GetProfessionTrend_Call struct {
	*mock.Call
}

// GetProfessionTrend is a helper method to define mock.On call
//   - ctx context.Context
//   - professionID uuid.UUID
func (_e *MockCacheProvider_Expecter) GetProfessionTrend(ctx interface{}, professionID interface{}) *MockCacheProvider_GetProfessionTrend_Call {
	return &MockCacheProvider_GetProfessionTrend_Call{Call: _e.mock.On("GetProfessionTrend", ctx, professionID)}
}

func (_c *MockCacheProvider_GetProfessionTrend_Call) Run(run func(ctx context.Context, professionID uuid.UUID)) *MockCacheProvider_GetProfessionTrend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCacheProvider_GetProfessionTrend_Call) Return(professionTrend *domain.ProfessionTrend, err error) *MockCacheProvider_GetProfessionTrend_Call {
	_c.Call.Return(professionTrend, err)
	return _c
}

func (_c *MockCacheProvider_GetProfessionTrend_Call) RunAndReturn(run func(ctx context.Context, professionID uuid.UUID) (*domain.ProfessionTrend, error)) *MockCacheProvider_GetProfessionTrend_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfessionsList provides a mock function for the type MockCacheProvider
func (_mock *MockCacheProvider) GetProfessionsList(ctx context.Context) ([]domain.ActiveProfession, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetProfessionsList")
	}

	var r0 []domain.ActiveProfession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.ActiveProfession, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.ActiveProfession); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ActiveProfession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCacheProvider_GetProfessionsList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfessionsList'
type MockCacheProvider_GetProfessionsList_Call struct {
	*mock.Call
}

// GetProfessionsList is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCacheProvider_Expecter) GetProfessionsList(ctx interface{}) *MockCacheProvider_GetProfessionsList_Call {
	return &MockCacheProvider_GetProfessionsList_Call{Call: _e.mock.On("GetProfessionsList", ctx)}
}

func (_c *MockCacheProvider_GetProfessionsList_Call) Run(run func(ctx context.Context)) *MockCacheProvider_GetProfessionsList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCacheProvider_GetProfessionsList_Call) Return(activeProfessions []domain.ActiveProfession, err error) *MockCacheProvider_GetProfessionsList_Call {
	_c.Call.Return(activeProfessions, err)
	return _c
}

func (_c *MockCacheProvider_GetProfessionsList_Call) RunAndReturn(run func(ctx context.Context) ([]domain.ActiveProfession, error)) *MockCacheProvider_GetProfessionsList_Call {
	_c.Call.Return(run)
	return _c
}

// SaveProfessionData provides a mock function for the type MockCacheProvider
func (_mock *MockCacheProvider) SaveProfessionData(ctx context.Context, data *domain.ProfessionDetail) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for SaveProfessionData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.ProfessionDetail) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCacheProvider_SaveProfessionData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveProfessionData'
type MockCacheProvider_SaveProfessionData_Call struct {
	*mock.Call
}

// SaveProfessionData is a helper method to define mock.On call
//   - ctx context.Context
//   - data *domain.ProfessionDetail
func (_e *MockCacheProvider_Expecter) SaveProfessionData(ctx interface{}, data interface{}) *MockCacheProvider_SaveProfessionData_Call {
	return &MockCacheProvider_SaveProfessionData_Call{Call: _e.mock.On("SaveProfessionData", ctx, data)}
}

func (_c *MockCacheProvider_SaveProfessionData_Call) Run(run func(ctx context.Context, data *domain.ProfessionDetail)) *MockCacheProvider_SaveProfessionData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.ProfessionDetail
		if args[1] != nil {
			arg1 = args[1].(*domain.ProfessionDetail)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCacheProvider_SaveProfessionData_Call) Return(err error) *MockCacheProvider_SaveProfessionData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCacheProvider_SaveProfessionData_Call) RunAndReturn(run func(ctx context.Context, data *domain.ProfessionDetail) error) *MockCacheProvider_SaveProfessionData_Call {
	_c.Call.Return(run)
	return _c
}

// SaveProfessionTrend provides a mock function for the type MockCacheProvider
func (_mock *MockCacheProvider) SaveProfessionTrend(ctx context.Context, professionID uuid.UUID, trend *domain.ProfessionTrend) error {
	ret := _mock.Called(ctx, professionID, trend)

	if len(ret) == 0 {
		panic("no return value specified for SaveProfessionTrend")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.ProfessionTrend) error); ok {
		r0 = returnFunc(ctx, professionID, trend)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCacheProvider_SaveProfessionTrend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveProfessionTrend'
type MockCacheProvider_SaveProfessionTrend_Call struct {
	*mock.Call
}

// SaveProfessionTrend is a helper method to define mock.On call
//   - ctx context.Context
//   - professionID uuid.UUID
//   - trend *domain.ProfessionTrend
func (_e *MockCacheProvider_Expecter) SaveProfessionTrend(ctx interface{}, professionID interface{}, trend interface{}) *MockCacheProvider_SaveProfessionTrend_Call {
	return &MockCacheProvider_SaveProfessionTrend_Call{Call: _e.mock.On("SaveProfessionTrend", ctx, professionID, trend)}
}

func (_c *MockCacheProvider_SaveProfessionTrend_Call) Run(run func(ctx context.Context, professionID uuid.UUID, trend *domain.ProfessionTrend)) *MockCacheProvider_SaveProfessionTrend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *domain.ProfessionTrend
		if args[2] != nil {
			arg2 = args[2].(*domain.ProfessionTrend)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCacheProvider_SaveProfessionTrend_Call) Return(err error) *MockCacheProvider_SaveProfessionTrend_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCacheProvider_SaveProfessionTrend_Call) RunAndReturn(run func(ctx context.Context, professionID uuid.UUID, trend *domain.ProfessionTrend) error) *MockCacheProvider_SaveProfessionTrend_Call {
	_c.Call.Return(run)
	return _c
}

// SaveProfessionsList provides a mock function for the type MockCacheProvider
func (_mock *MockCacheProvider) SaveProfessionsList(ctx context.Context, professions []domain.ActiveProfession) error {
	ret := _mock.Called(ctx, professions)

	if len(ret) == 0 {
		panic("no return value specified for SaveProfessionsList")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.ActiveProfession) error); ok {
		r0 = returnFunc(ctx, professions)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCacheProvider_SaveProfessionsList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveProfessionsList'
type MockCacheProvider_SaveProfessionsList_Call struct {
	*mock.Call
}

// SaveProfessionsList is a helper method to define mock.On call
//   - ctx context.Context
//   - professions []domain.ActiveProfession
func (_e *MockCacheProvider_Expecter) SaveProfessionsList(ctx interface{}, professions interface{}) *MockCacheProvider_SaveProfessionsList_Call {
	return &MockCacheProvider_SaveProfessionsList_Call{Call: _e.mock.On("SaveProfessionsList", ctx, professions)}
}

func (_c *MockCacheProvider_SaveProfessionsList_Call) Run(run func(ctx context.Context, professions []domain.ActiveProfession)) *MockCacheProvider_SaveProfessionsList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []domain.ActiveProfession
		if args[1] != nil {
			arg1 = args[1].([]domain.ActiveProfession)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCacheProvider_SaveProfessionsList_Call) Return(err error) *MockCacheProvider_SaveProfessionsList_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCacheProvider_SaveProfessionsList_Call) RunAndReturn(run func(ctx context.Context, professions []domain.ActiveProfession) error) *MockCacheProvider_SaveProfessionsList_Call {
	_c.Call.Return(run)
	return _c
}
