// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"psa/internal/domain"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDailyStatProvider creates a new instance of MockDailyStatProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDailyStatProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDailyStatProvider {
	mock := &MockDailyStatProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDailyStatProvider is an autogenerated mock type for the DailyStatProvider type
type MockDailyStatProvider struct {
	mock.Mock
}

type MockDailyStatProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDailyStatProvider) EXPECT() *MockDailyStatProvider_Expecter {
	return &MockDailyStatProvider_Expecter{mock: &_m.Mock}
}

// GetStatDailyByProfessionID provides a mock function for the type MockDailyStatProvider
func (_mock *MockDailyStatProvider) GetStatDailyByProfessionID(ctx context.Context, professionID uuid.UUID) ([]domain.StatDailyPoint, error) {
	ret := _mock.Called(ctx, professionID)

	if len(ret) == 0 {
		panic("no return value specified for GetStatDailyByProfessionID")
	}

	var r0 []domain.StatDailyPoint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.StatDailyPoint, error)); ok {
		return returnFunc(ctx, professionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.StatDailyPoint); ok {
		r0 = returnFunc(ctx, professionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.StatDailyPoint)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, professionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDailyStatProvider_GetStatDailyByProfessionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatDailyByProfessionID'
type MockDailyStatProvider_GetStatDailyByProfessionID_Call struct {
	*mock.Call
}

// GetStatDailyByProfessionID is a helper method to define mock.On call
//   - ctx context.Context
//   - professionID uuid.UUID
func (_e *MockDailyStatProvider_Expecter) GetStatDailyByProfessionID(ctx interface{}, professionID interface{}) *MockDailyStatProvider_GetStatDailyByProfessionID_Call {
	return &MockDailyStatProvider_GetStatDailyByProfessionID_Call{Call: _e.mock.On("GetStatDailyByProfessionID", ctx, professionID)}
}

func (_c *MockDailyStatProvider_GetStatDailyByProfessionID_Call) Run(run func(ctx context.Context, professionID uuid.UUID)) *MockDailyStatProvider_GetStatDailyByProfessionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDailyStatProvider_GetStatDailyByProfessionID_Call) Return(statDailyPoints []domain.StatDailyPoint, err error) *MockDailyStatProvider_GetStatDailyByProfessionID_Call {
	_c.Call.Return(statDailyPoints, err)
	return _c
}

func (_c *MockDailyStatProvider_GetStatDailyByProfessionID_Call) RunAndReturn(run func(ctx context.Context, professionID uuid.UUID) ([]domain.StatDailyPoint, error)) *MockDailyStatProvider_GetStatDailyByProfessionID_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatDailyByProfessionIDs provides a mock function for the type MockDailyStatProvider
func (_mock *MockDailyStatProvider) GetStatDailyByProfessionIDs(ctx context.Context, professionIDs []uuid.UUID) (map[uuid.UUID][]domain.StatDailyPoint, error) {
	ret := _mock.Called(ctx, professionIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetStatDailyByProfessionIDs")
	}

	var r0 map[uuid.UUID][]domain.StatDailyPoint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) (map[uuid.UUID][]domain.StatDailyPoint, error)); ok {
		return returnFunc(ctx, professionIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) map[uuid.UUID][]domain.StatDailyPoint); ok {
		r0 = returnFunc(ctx, professionIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID][]domain.StatDailyPoint)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, professionIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDailyStatProvider_GetStatDailyByProfessionIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatDailyByProfessionIDs'
type MockDailyStatProvider_GetStatDailyByProfessionIDs_Call struct {
	*mock.Call
}

// GetStatDailyByProfessionIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - professionIDs []uuid.UUID
func (_e *MockDailyStatProvider_Expecter) GetStatDailyByProfessionIDs(ctx interface{}, professionIDs interface{}) *MockDailyStatProvider_GetStatDailyByProfessionIDs_Call {
	return &MockDailyStatProvider_GetStatDailyByProfessionIDs_Call{Call: _e.mock.On("GetStatDailyByProfessionIDs", ctx, professionIDs)}
}

func (_c *MockDailyStatProvider_GetStatDailyByProfessionIDs_Call) Run(run func(ctx context.Context, professionIDs []uuid.UUID)) *MockDailyStatProvider_GetStatDailyByProfessionIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDailyStatProvider_GetStatDailyByProfessionIDs_Call) Return(uUIDToStatDailyPoints map[uuid.UUID][]domain.StatDailyPoint, err error) *MockDailyStatProvider_GetStatDailyByProfessionIDs_Call {
	_c.Call.Return(uUIDToStatDailyPoints, err)
	return _c
}

func (_c *MockDailyStatProvider_GetStatDailyByProfessionIDs_Call) RunAndReturn(run func(ctx context.Context, professionIDs []uuid.UUID) (map[uuid.UUID][]domain.StatDailyPoint, error)) *MockDailyStatProvider_GetStatDailyByProfessionIDs_Call {
	_c.Call.Return(run)
	return _c
}
