// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"psa/internal/domain"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProfessionProvider creates a new instance of MockProfessionProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfessionProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfessionProvider {
	mock := &MockProfessionProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProfessionProvider is an autogenerated mock type for the ProfessionProvider type
type MockProfessionProvider struct {
	mock.Mock
}

type MockProfessionProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProfessionProvider) EXPECT() *MockProfessionProvider_Expecter {
	return &MockProfessionProvider_Expecter{mock: &_m.Mock}
}

// AddProfession provides a mock function for the type MockProfessionProvider
func (_mock *MockProfessionProvider) AddProfession(ctx context.Context, profession domain.Profession) (uuid.UUID, error) {
	ret := _mock.Called(ctx, profession)

	if len(ret) == 0 {
		panic("no return value specified for AddProfession")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Profession) (uuid.UUID, error)); ok {
		return returnFunc(ctx, profession)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Profession) uuid.UUID); ok {
		r0 = returnFunc(ctx, profession)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Profession) error); ok {
		r1 = returnFunc(ctx, profession)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfessionProvider_AddProfession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddProfession'
type MockProfessionProvider_AddProfession_Call struct {
	*mock.Call
}

// AddProfession is a helper method to define mock.On call
//   - ctx context.Context
//   - profession domain.Profession
func (_e *MockProfessionProvider_Expecter) AddProfession(ctx interface{}, profession interface{}) *MockProfessionProvider_AddProfession_Call {
	return &MockProfessionProvider_AddProfession_Call{Call: _e.mock.On("AddProfession", ctx, profession)}
}

func (_c *MockProfessionProvider_AddProfession_Call) Run(run func(ctx context.Context, profession domain.Profession)) *MockProfessionProvider_AddProfession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Profession
		if args[1] != nil {
			arg1 = args[1].(domain.Profession)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfessionProvider_AddProfession_Call) Return(uUID uuid.UUID, err error) *MockProfessionProvider_AddProfession_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockProfessionProvider_AddProfession_Call) RunAndReturn(run func(ctx context.Context, profession domain.Profession) (uuid.UUID, error)) *MockProfessionProvider_AddProfession_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveProfessions provides a mock function for the type MockProfessionProvider
func (_mock *MockProfessionProvider) GetActiveProfessions(ctx context.Context) ([]domain.Profession, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveProfessions")
	}

	var r0 []domain.Profession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.Profession, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Profession); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Profession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfessionProvider_GetActiveProfessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveProfessions'
type MockProfessionProvider_GetActiveProfessions_Call struct {
	*mock.Call
}

// GetActiveProfessions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProfessionProvider_Expecter) GetActiveProfessions(ctx interface{}) *MockProfessionProvider_GetActiveProfessions_Call {
	return &MockProfessionProvider_GetActiveProfessions_Call{Call: _e.mock.On("GetActiveProfessions", ctx)}
}

func (_c *MockProfessionProvider_GetActiveProfessions_Call) Run(run func(ctx context.Context)) *MockProfessionProvider_GetActiveProfessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProfessionProvider_GetActiveProfessions_Call) Return(professions []domain.Profession, err error) *MockProfessionProvider_GetActiveProfessions_Call {
	_c.Call.Return(professions, err)
	return _c
}

func (_c *MockProfessionProvider_GetActiveProfessions_Call) RunAndReturn(run func(ctx context.Context) ([]domain.Profession, error)) *MockProfessionProvider_GetActiveProfessions_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllProfessions provides a mock function for the type MockProfessionProvider
func (_mock *MockProfessionProvider) GetAllProfessions(ctx context.Context) ([]domain.Profession, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllProfessions")
	}

	var r0 []domain.Profession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.Profession, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Profession); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Profession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfessionProvider_GetAllProfessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllProfessions'
type MockProfessionProvider_GetAllProfessions_Call struct {
	*mock.Call
}

// GetAllProfessions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProfessionProvider_Expecter) GetAllProfessions(ctx interface{}) *MockProfessionProvider_GetAllProfessions_Call {
	return &MockProfessionProvider_GetAllProfessions_Call{Call: _e.mock.On("GetAllProfessions", ctx)}
}

func (_c *MockProfessionProvider_GetAllProfessions_Call) Run(run func(ctx context.Context)) *MockProfessionProvider_GetAllProfessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProfessionProvider_GetAllProfessions_Call) Return(professions []domain.Profession, err error) *MockProfessionProvider_GetAllProfessions_Call {
	_c.Call.Return(professions, err)
	return _c
}

func (_c *MockProfessionProvider_GetAllProfessions_Call) RunAndReturn(run func(ctx context.Context) ([]domain.Profession, error)) *MockProfessionProvider_GetAllProfessions_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfessionByID provides a mock function for the type MockProfessionProvider
func (_mock *MockProfessionProvider) GetProfessionByID(ctx context.Context, id uuid.UUID) (domain.Profession, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProfessionByID")
	}

	var r0 domain.Profession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Profession, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Profession); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Profession)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfessionProvider_GetProfessionByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfessionByID'
type MockProfessionProvider_GetProfessionByID_Call struct {
	*mock.Call
}

// GetProfessionByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockProfessionProvider_Expecter) GetProfessionByID(ctx interface{}, id interface{}) *MockProfessionProvider_GetProfessionByID_Call {
	return &MockProfessionProvider_GetProfessionByID_Call{Call: _e.mock.On("GetProfessionByID", ctx, id)}
}

func (_c *MockProfessionProvider_GetProfessionByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockProfessionProvider_GetProfessionByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfessionProvider_GetProfessionByID_Call) Return(profession domain.Profession, err error) *MockProfessionProvider_GetProfessionByID_Call {
	_c.Call.Return(profession, err)
	return _c
}

func (_c *MockProfessionProvider_GetProfessionByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.Profession, error)) *MockProfessionProvider_GetProfessionByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfessionByName provides a mock function for the type MockProfessionProvider
func (_mock *MockProfessionProvider) GetProfessionByName(ctx context.Context, name string) (domain.Profession, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetProfessionByName")
	}

	var r0 domain.Profession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.Profession, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.Profession); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(domain.Profession)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfessionProvider_GetProfessionByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfessionByName'
type MockProfessionProvider_GetProfessionByName_Call struct {
	*mock.Call
}

// GetProfessionByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockProfessionProvider_Expecter) GetProfessionByName(ctx interface{}, name interface{}) *MockProfessionProvider_GetProfessionByName_Call {
	return &MockProfessionProvider_GetProfessionByName_Call{Call: _e.mock.On("GetProfessionByName", ctx, name)}
}

func (_c *MockProfessionProvider_GetProfessionByName_Call) Run(run func(ctx context.Context, name string)) *MockProfessionProvider_GetProfessionByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfessionProvider_GetProfessionByName_Call) Return(profession domain.Profession, err error) *MockProfessionProvider_GetProfessionByName_Call {
	_c.Call.Return(profession, err)
	return _c
}

func (_c *MockProfessionProvider_GetProfessionByName_Call) RunAndReturn(run func(ctx context.Context, name string) (domain.Profession, error)) *MockProfessionProvider_GetProfessionByName_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfession provides a mock function for the type MockProfessionProvider
func (_mock *MockProfessionProvider) UpdateProfession(ctx context.Context, profession domain.Profession) error {
	ret := _mock.Called(ctx, profession)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Profession) error); ok {
		r0 = returnFunc(ctx, profession)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProfessionProvider_UpdateProfession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfession'
type MockProfessionProvider_UpdateProfession_Call struct {
	*mock.Call
}

// UpdateProfession is a helper method to define mock.On call
//   - ctx context.Context
//   - profession domain.Profession
func (_e *MockProfessionProvider_Expecter) UpdateProfession(ctx interface{}, profession interface{}) *MockProfessionProvider_UpdateProfession_Call {
	return &MockProfessionProvider_UpdateProfession_Call{Call: _e.mock.On("UpdateProfession", ctx, profession)}
}

func (_c *MockProfessionProvider_UpdateProfession_Call) Run(run func(ctx context.Context, profession domain.Profession)) *MockProfessionProvider_UpdateProfession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Profession
		if args[1] != nil {
			arg1 = args[1].(domain.Profession)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfessionProvider_UpdateProfession_Call) Return(err error) *MockProfessionProvider_UpdateProfession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProfessionProvider_UpdateProfession_Call) RunAndReturn(run func(ctx context.Context, profession domain.Profession) error) *MockProfessionProvider_UpdateProfession_Call {
	_c.Call.Return(run)
	return _c
}
