// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"psa/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionProvider creates a new instance of MockSessionProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionProvider {
	mock := &MockSessionProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionProvider is an autogenerated mock type for the SessionProvider type
type MockSessionProvider struct {
	mock.Mock
}

type MockSessionProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionProvider) EXPECT() *MockSessionProvider_Expecter {
	return &MockSessionProvider_Expecter{mock: &_m.Mock}
}

// GetLatestScraping provides a mock function for the type MockSessionProvider
func (_mock *MockSessionProvider) GetLatestScraping(ctx context.Context) (domain.Scraping, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestScraping")
	}

	var r0 domain.Scraping
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (domain.Scraping, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) domain.Scraping); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(domain.Scraping)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionProvider_GetLatestScraping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestScraping'
type MockSessionProvider_GetLatestScraping_Call struct {
	*mock.Call
}

// GetLatestScraping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSessionProvider_Expecter) GetLatestScraping(ctx interface{}) *MockSessionProvider_GetLatestScraping_Call {
	return &MockSessionProvider_GetLatestScraping_Call{Call: _e.mock.On("GetLatestScraping", ctx)}
}

func (_c *MockSessionProvider_GetLatestScraping_Call) Run(run func(ctx context.Context)) *MockSessionProvider_GetLatestScraping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSessionProvider_GetLatestScraping_Call) Return(scraping domain.Scraping, err error) *MockSessionProvider_GetLatestScraping_Call {
	_c.Call.Return(scraping, err)
	return _c
}

func (_c *MockSessionProvider_GetLatestScraping_Call) RunAndReturn(run func(ctx context.Context) (domain.Scraping, error)) *MockSessionProvider_GetLatestScraping_Call {
	_c.Call.Return(run)
	return _c
}
