// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"psa/internal/domain"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSkillsProvider creates a new instance of MockSkillsProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSkillsProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSkillsProvider {
	mock := &MockSkillsProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSkillsProvider is an autogenerated mock type for the SkillsProvider type
type MockSkillsProvider struct {
	mock.Mock
}

type MockSkillsProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSkillsProvider) EXPECT() *MockSkillsProvider_Expecter {
	return &MockSkillsProvider_Expecter{mock: &_m.Mock}
}

// GetExtractedSkillsByProfessionAndDate provides a mock function for the type MockSkillsProvider
func (_mock *MockSkillsProvider) GetExtractedSkillsByProfessionAndDate(ctx context.Context, professionID uuid.UUID, scrapedAtID uuid.UUID) ([]domain.Skill, error) {
	ret := _mock.Called(ctx, professionID, scrapedAtID)

	if len(ret) == 0 {
		panic("no return value specified for GetExtractedSkillsByProfessionAndDate")
	}

	var r0 []domain.Skill
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]domain.Skill, error)); ok {
		return returnFunc(ctx, professionID, scrapedAtID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []domain.Skill); ok {
		r0 = returnFunc(ctx, professionID, scrapedAtID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Skill)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, professionID, scrapedAtID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSkillsProvider_GetExtractedSkillsByProfessionAndDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExtractedSkillsByProfessionAndDate'
type MockSkillsProvider_GetExtractedSkillsByProfessionAndDate_Call struct {
	*mock.Call
}

// GetExtractedSkillsByProfessionAndDate is a helper method to define mock.On call
//   - ctx context.Context
//   - professionID uuid.UUID
//   - scrapedAtID uuid.UUID
func (_e *MockSkillsProvider_Expecter) GetExtractedSkillsByProfessionAndDate(ctx interface{}, professionID interface{}, scrapedAtID interface{}) *MockSkillsProvider_GetExtractedSkillsByProfessionAndDate_Call {
	return &MockSkillsProvider_GetExtractedSkillsByProfessionAndDate_Call{Call: _e.mock.On("GetExtractedSkillsByProfessionAndDate", ctx, professionID, scrapedAtID)}
}

func (_c *MockSkillsProvider_GetExtractedSkillsByProfessionAndDate_Call) Run(run func(ctx context.Context, professionID uuid.UUID, scrapedAtID uuid.UUID)) *MockSkillsProvider_GetExtractedSkillsByProfessionAndDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSkillsProvider_GetExtractedSkillsByProfessionAndDate_Call) Return(skills []domain.Skill, err error) *MockSkillsProvider_GetExtractedSkillsByProfessionAndDate_Call {
	_c.Call.Return(skills, err)
	return _c
}

func (_c *MockSkillsProvider_GetExtractedSkillsByProfessionAndDate_Call) RunAndReturn(run func(ctx context.Context, professionID uuid.UUID, scrapedAtID uuid.UUID) ([]domain.Skill, error)) *MockSkillsProvider_GetExtractedSkillsByProfessionAndDate_Call {
	_c.Call.Return(run)
	return _c
}

// GetFormalSkillsByProfessionAndDate provides a mock function for the type MockSkillsProvider
func (_mock *MockSkillsProvider) GetFormalSkillsByProfessionAndDate(ctx context.Context, professionID uuid.UUID, scrapedAtID uuid.UUID) ([]domain.Skill, error) {
	ret := _mock.Called(ctx, professionID, scrapedAtID)

	if len(ret) == 0 {
		panic("no return value specified for GetFormalSkillsByProfessionAndDate")
	}

	var r0 []domain.Skill
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]domain.Skill, error)); ok {
		return returnFunc(ctx, professionID, scrapedAtID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []domain.Skill); ok {
		r0 = returnFunc(ctx, professionID, scrapedAtID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Skill)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, professionID, scrapedAtID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSkillsProvider_GetFormalSkillsByProfessionAndDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFormalSkillsByProfessionAndDate'
type MockSkillsProvider_GetFormalSkillsByProfessionAndDate_Call struct {
	*mock.Call
}

// GetFormalSkillsByProfessionAndDate is a helper method to define mock.On call
//   - ctx context.Context
//   - professionID uuid.UUID
//   - scrapedAtID uuid.UUID
func (_e *MockSkillsProvider_Expecter) GetFormalSkillsByProfessionAndDate(ctx interface{}, professionID interface{}, scrapedAtID interface{}) *MockSkillsProvider_GetFormalSkillsByProfessionAndDate_Call {
	return &MockSkillsProvider_GetFormalSkillsByProfessionAndDate_Call{Call: _e.mock.On("GetFormalSkillsByProfessionAndDate", ctx, professionID, scrapedAtID)}
}

func (_c *MockSkillsProvider_GetFormalSkillsByProfessionAndDate_Call) Run(run func(ctx context.Context, professionID uuid.UUID, scrapedAtID uuid.UUID)) *MockSkillsProvider_GetFormalSkillsByProfessionAndDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSkillsProvider_GetFormalSkillsByProfessionAndDate_Call) Return(skills []domain.Skill, err error) *MockSkillsProvider_GetFormalSkillsByProfessionAndDate_Call {
	_c.Call.Return(skills, err)
	return _c
}

func (_c *MockSkillsProvider_GetFormalSkillsByProfessionAndDate_Call) RunAndReturn(run func(ctx context.Context, professionID uuid.UUID, scrapedAtID uuid.UUID) ([]domain.Skill, error)) *MockSkillsProvider_GetFormalSkillsByProfessionAndDate_Call {
	_c.Call.Return(run)
	return _c
}
