// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"psa/internal/domain"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStatProvider creates a new instance of MockStatProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatProvider {
	mock := &MockStatProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStatProvider is an autogenerated mock type for the StatProvider type
type MockStatProvider struct {
	mock.Mock
}

type MockStatProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatProvider) EXPECT() *MockStatProvider_Expecter {
	return &MockStatProvider_Expecter{mock: &_m.Mock}
}

// GetLatestStatByProfessionID provides a mock function for the type MockStatProvider
func (_mock *MockStatProvider) GetLatestStatByProfessionID(ctx context.Context, professionID uuid.UUID) (domain.Stat, error) {
	ret := _mock.Called(ctx, professionID)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestStatByProfessionID")
	}

	var r0 domain.Stat
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Stat, error)); ok {
		return returnFunc(ctx, professionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Stat); ok {
		r0 = returnFunc(ctx, professionID)
	} else {
		r0 = ret.Get(0).(domain.Stat)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, professionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStatProvider_GetLatestStatByProfessionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestStatByProfessionID'
type MockStatProvider_GetLatestStatByProfessionID_Call struct {
	*mock.Call
}

// GetLatestStatByProfessionID is a helper method to define mock.On call
//   - ctx context.Context
//   - professionID uuid.UUID
func (_e *MockStatProvider_Expecter) GetLatestStatByProfessionID(ctx interface{}, professionID interface{}) *MockStatProvider_GetLatestStatByProfessionID_Call {
	return &MockStatProvider_GetLatestStatByProfessionID_Call{Call: _e.mock.On("GetLatestStatByProfessionID", ctx, professionID)}
}

func (_c *MockStatProvider_GetLatestStatByProfessionID_Call) Run(run func(ctx context.Context, professionID uuid.UUID)) *MockStatProvider_GetLatestStatByProfessionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStatProvider_GetLatestStatByProfessionID_Call) Return(stat domain.Stat, err error) *MockStatProvider_GetLatestStatByProfessionID_Call {
	_c.Call.Return(stat, err)
	return _c
}

func (_c *MockStatProvider_GetLatestStatByProfessionID_Call) RunAndReturn(run func(ctx context.Context, professionID uuid.UUID) (domain.Stat, error)) *MockStatProvider_GetLatestStatByProfessionID_Call {
	_c.Call.Return(run)
	return _c
}
