all: false
dir: ""
filename: "{{.InterfaceName}}.go"
structname: "Mock{{.InterfaceName}}"
pkgname: mocks
template: testify

packages:
  # Auth service
  psa/internal/service/auth:
    interfaces:
      UserProvider:
      RefreshTokenProvider:
      JWTProvider:
    config:
      dir: internal/service/auth/mocks

  # Scraper service
  psa/internal/service/scraper:
    interfaces:
      ProfessionProvider:
      SessionProvider:
      SkillsProvider:
      StatProvider:
      DailyStatProvider:
      SupplierPort:
      Extractor:
      CacheProvider:
    config:
      dir: internal/service/scraper/mocks

  # Provider service
  psa/internal/service/provider:
    interfaces:
      ProfessionProvider:
      SessionProvider:
      StatProvider:
      SkillsProvider:
      CacheProvider:
      DailyStatProvider:
    config:
      dir: internal/service/provider/mocks