// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"psa/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCacheProvider creates a new instance of MockCacheProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCacheProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCacheProvider {
	mock := &MockCacheProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCacheProvider is an autogenerated mock type for the CacheProvider type
type MockCacheProvider struct {
	mock.Mock
}

type MockCacheProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCacheProvider) EXPECT() *MockCacheProvider_Expecter {
	return &MockCacheProvider_Expecter{mock: &_m.Mock}
}

// SaveProfessionData provides a mock function for the type MockCacheProvider
func (_mock *MockCacheProvider) SaveProfessionData(ctx context.Context, data *domain.ProfessionDetail) error {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for SaveProfessionData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.ProfessionDetail) error); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCacheProvider_SaveProfessionData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveProfessionData'
type MockCacheProvider_SaveProfessionData_Call struct {
	*mock.Call
}

// SaveProfessionData is a helper method to define mock.On call
//   - ctx context.Context
//   - data *domain.ProfessionDetail
func (_e *MockCacheProvider_Expecter) SaveProfessionData(ctx interface{}, data interface{}) *MockCacheProvider_SaveProfessionData_Call {
	return &MockCacheProvider_SaveProfessionData_Call{Call: _e.mock.On("SaveProfessionData", ctx, data)}
}

func (_c *MockCacheProvider_SaveProfessionData_Call) Run(run func(ctx context.Context, data *domain.ProfessionDetail)) *MockCacheProvider_SaveProfessionData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.ProfessionDetail
		if args[1] != nil {
			arg1 = args[1].(*domain.ProfessionDetail)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCacheProvider_SaveProfessionData_Call) Return(err error) *MockCacheProvider_SaveProfessionData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCacheProvider_SaveProfessionData_Call) RunAndReturn(run func(ctx context.Context, data *domain.ProfessionDetail) error) *MockCacheProvider_SaveProfessionData_Call {
	_c.Call.Return(run)
	return _c
}
