// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDailyStatProvider creates a new instance of MockDailyStatProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDailyStatProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDailyStatProvider {
	mock := &MockDailyStatProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDailyStatProvider is an autogenerated mock type for the DailyStatProvider type
type MockDailyStatProvider struct {
	mock.Mock
}

type MockDailyStatProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDailyStatProvider) EXPECT() *MockDailyStatProvider_Expecter {
	return &MockDailyStatProvider_Expecter{mock: &_m.Mock}
}

// SaveStatDaily provides a mock function for the type MockDailyStatProvider
func (_mock *MockDailyStatProvider) SaveStatDaily(ctx context.Context, professionID uuid.UUID, vacancyCount int, scrapedAt time.Time) error {
	ret := _mock.Called(ctx, professionID, vacancyCount, scrapedAt)

	if len(ret) == 0 {
		panic("no return value specified for SaveStatDaily")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, time.Time) error); ok {
		r0 = returnFunc(ctx, professionID, vacancyCount, scrapedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDailyStatProvider_SaveStatDaily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveStatDaily'
type MockDailyStatProvider_SaveStatDaily_Call struct {
	*mock.Call
}

// SaveStatDaily is a helper method to define mock.On call
//   - ctx context.Context
//   - professionID uuid.UUID
//   - vacancyCount int
//   - scrapedAt time.Time
func (_e *MockDailyStatProvider_Expecter) SaveStatDaily(ctx interface{}, professionID interface{}, vacancyCount interface{}, scrapedAt interface{}) *MockDailyStatProvider_SaveStatDaily_Call {
	return &MockDailyStatProvider_SaveStatDaily_Call{Call: _e.mock.On("SaveStatDaily", ctx, professionID, vacancyCount, scrapedAt)}
}

func (_c *MockDailyStatProvider_SaveStatDaily_Call) Run(run func(ctx context.Context, professionID uuid.UUID, vacancyCount int, scrapedAt time.Time)) *MockDailyStatProvider_SaveStatDaily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDailyStatProvider_SaveStatDaily_Call) Return(err error) *MockDailyStatProvider_SaveStatDaily_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDailyStatProvider_SaveStatDaily_Call) RunAndReturn(run func(ctx context.Context, professionID uuid.UUID, vacancyCount int, scrapedAt time.Time) error) *MockDailyStatProvider_SaveStatDaily_Call {
	_c.Call.Return(run)
	return _c
}
