// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockExtractor creates a new instance of MockExtractor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExtractor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExtractor {
	mock := &MockExtractor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExtractor is an autogenerated mock type for the Extractor type
type MockExtractor struct {
	mock.Mock
}

type MockExtractor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExtractor) EXPECT() *MockExtractor_Expecter {
	return &MockExtractor_Expecter{mock: &_m.Mock}
}

// ExtractSkills provides a mock function for the type MockExtractor
func (_mock *MockExtractor) ExtractSkills(text string, whiteList map[string]int, maxNgram int) (map[string]int, error) {
	ret := _mock.Called(text, whiteList, maxNgram)

	if len(ret) == 0 {
		panic("no return value specified for ExtractSkills")
	}

	var r0 map[string]int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, map[string]int, int) (map[string]int, error)); ok {
		return returnFunc(text, whiteList, maxNgram)
	}
	if returnFunc, ok := ret.Get(0).(func(string, map[string]int, int) map[string]int); ok {
		r0 = returnFunc(text, whiteList, maxNgram)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, map[string]int, int) error); ok {
		r1 = returnFunc(text, whiteList, maxNgram)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExtractor_ExtractSkills_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractSkills'
type MockExtractor_ExtractSkills_Call struct {
	*mock.Call
}

// ExtractSkills is a helper method to define mock.On call
//   - text string
//   - whiteList map[string]int
//   - maxNgram int
func (_e *MockExtractor_Expecter) ExtractSkills(text interface{}, whiteList interface{}, maxNgram interface{}) *MockExtractor_ExtractSkills_Call {
	return &MockExtractor_ExtractSkills_Call{Call: _e.mock.On("ExtractSkills", text, whiteList, maxNgram)}
}

func (_c *MockExtractor_ExtractSkills_Call) Run(run func(text string, whiteList map[string]int, maxNgram int)) *MockExtractor_ExtractSkills_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 map[string]int
		if args[1] != nil {
			arg1 = args[1].(map[string]int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockExtractor_ExtractSkills_Call) Return(stringToInt map[string]int, err error) *MockExtractor_ExtractSkills_Call {
	_c.Call.Return(stringToInt, err)
	return _c
}

func (_c *MockExtractor_ExtractSkills_Call) RunAndReturn(run func(text string, whiteList map[string]int, maxNgram int) (map[string]int, error)) *MockExtractor_ExtractSkills_Call {
	_c.Call.Return(run)
	return _c
}
