// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"psa/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockProfessionProvider creates a new instance of MockProfessionProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfessionProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfessionProvider {
	mock := &MockProfessionProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProfessionProvider is an autogenerated mock type for the ProfessionProvider type
type MockProfessionProvider struct {
	mock.Mock
}

type MockProfessionProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProfessionProvider) EXPECT() *MockProfessionProvider_Expecter {
	return &MockProfessionProvider_Expecter{mock: &_m.Mock}
}

// GetActiveProfessions provides a mock function for the type MockProfessionProvider
func (_mock *MockProfessionProvider) GetActiveProfessions(ctx context.Context) ([]domain.Profession, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveProfessions")
	}

	var r0 []domain.Profession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.Profession, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Profession); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Profession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfessionProvider_GetActiveProfessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveProfessions'
type MockProfessionProvider_GetActiveProfessions_Call struct {
	*mock.Call
}

// GetActiveProfessions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProfessionProvider_Expecter) GetActiveProfessions(ctx interface{}) *MockProfessionProvider_GetActiveProfessions_Call {
	return &MockProfessionProvider_GetActiveProfessions_Call{Call: _e.mock.On("GetActiveProfessions", ctx)}
}

func (_c *MockProfessionProvider_GetActiveProfessions_Call) Run(run func(ctx context.Context)) *MockProfessionProvider_GetActiveProfessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProfessionProvider_GetActiveProfessions_Call) Return(professions []domain.Profession, err error) *MockProfessionProvider_GetActiveProfessions_Call {
	_c.Call.Return(professions, err)
	return _c
}

func (_c *MockProfessionProvider_GetActiveProfessions_Call) RunAndReturn(run func(ctx context.Context) ([]domain.Profession, error)) *MockProfessionProvider_GetActiveProfessions_Call {
	_c.Call.Return(run)
	return _c
}
