// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"psa/internal/domain"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockScrapeResultSaver creates a new instance of MockScrapeResultSaver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScrapeResultSaver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScrapeResultSaver {
	mock := &MockScrapeResultSaver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockScrapeResultSaver is an autogenerated mock type for the ScrapeResultSaver type
type MockScrapeResultSaver struct {
	mock.Mock
}

type MockScrapeResultSaver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScrapeResultSaver) EXPECT() *MockScrapeResultSaver_Expecter {
	return &MockScrapeResultSaver_Expecter{mock: &_m.Mock}
}

// SaveArchiveProfessionResult provides a mock function for the type MockScrapeResultSaver
func (_mock *MockScrapeResultSaver) SaveArchiveProfessionResult(ctx context.Context, sessionID uuid.UUID, scrapedAt time.Time, result domain.ProfessionScrapeResult) error {
	ret := _mock.Called(ctx, sessionID, scrapedAt, result)

	if len(ret) == 0 {
		panic("no return value specified for SaveArchiveProfessionResult")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time, domain.ProfessionScrapeResult) error); ok {
		r0 = returnFunc(ctx, sessionID, scrapedAt, result)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockScrapeResultSaver_SaveArchiveProfessionResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveArchiveProfessionResult'
type MockScrapeResultSaver_SaveArchiveProfessionResult_Call struct {
	*mock.Call
}

// SaveArchiveProfessionResult is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
//   - scrapedAt time.Time
//   - result domain.ProfessionScrapeResult
func (_e *MockScrapeResultSaver_Expecter) SaveArchiveProfessionResult(ctx interface{}, sessionID interface{}, scrapedAt interface{}, result interface{}) *MockScrapeResultSaver_SaveArchiveProfessionResult_Call {
	return &MockScrapeResultSaver_SaveArchiveProfessionResult_Call{Call: _e.mock.On("SaveArchiveProfessionResult", ctx, sessionID, scrapedAt, result)}
}

func (_c *MockScrapeResultSaver_SaveArchiveProfessionResult_Call) Run(run func(ctx context.Context, sessionID uuid.UUID, scrapedAt time.Time, result domain.ProfessionScrapeResult)) *MockScrapeResultSaver_SaveArchiveProfessionResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 domain.ProfessionScrapeResult
		if args[3] != nil {
			arg3 = args[3].(domain.ProfessionScrapeResult)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockScrapeResultSaver_SaveArchiveProfessionResult_Call) Return(err error) *MockScrapeResultSaver_SaveArchiveProfessionResult_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockScrapeResultSaver_SaveArchiveProfessionResult_Call) RunAndReturn(run func(ctx context.Context, sessionID uuid.UUID, scrapedAt time.Time, result domain.ProfessionScrapeResult) error) *MockScrapeResultSaver_SaveArchiveProfessionResult_Call {
	_c.Call.Return(run)
	return _c
}

// SaveDailyProfessionResult provides a mock function for the type MockScrapeResultSaver
func (_mock *MockScrapeResultSaver) SaveDailyProfessionResult(ctx context.Context, scrapedAt time.Time, result domain.ProfessionScrapeResult) error {
	ret := _mock.Called(ctx, scrapedAt, result)

	if len(ret) == 0 {
		panic("no return value specified for SaveDailyProfessionResult")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time, domain.ProfessionScrapeResult) error); ok {
		r0 = returnFunc(ctx, scrapedAt, result)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockScrapeResultSaver_SaveDailyProfessionResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveDailyProfessionResult'
type MockScrapeResultSaver_SaveDailyProfessionResult_Call struct {
	*mock.Call
}

// SaveDailyProfessionResult is a helper method to define mock.On call
//   - ctx context.Context
//   - scrapedAt time.Time
//   - result domain.ProfessionScrapeResult
func (_e *MockScrapeResultSaver_Expecter) SaveDailyProfessionResult(ctx interface{}, scrapedAt interface{}, result interface{}) *MockScrapeResultSaver_SaveDailyProfessionResult_Call {
	return &MockScrapeResultSaver_SaveDailyProfessionResult_Call{Call: _e.mock.On("SaveDailyProfessionResult", ctx, scrapedAt, result)}
}

func (_c *MockScrapeResultSaver_SaveDailyProfessionResult_Call) Run(run func(ctx context.Context, scrapedAt time.Time, result domain.ProfessionScrapeResult)) *MockScrapeResultSaver_SaveDailyProfessionResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 domain.ProfessionScrapeResult
		if args[2] != nil {
			arg2 = args[2].(domain.ProfessionScrapeResult)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockScrapeResultSaver_SaveDailyProfessionResult_Call) Return(err error) *MockScrapeResultSaver_SaveDailyProfessionResult_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockScrapeResultSaver_SaveDailyProfessionResult_Call) RunAndReturn(run func(ctx context.Context, scrapedAt time.Time, result domain.ProfessionScrapeResult) error) *MockScrapeResultSaver_SaveDailyProfessionResult_Call {
	_c.Call.Return(run)
	return _c
}
