// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionProvider creates a new instance of MockSessionProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionProvider {
	mock := &MockSessionProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionProvider is an autogenerated mock type for the SessionProvider type
type MockSessionProvider struct {
	mock.Mock
}

type MockSessionProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionProvider) EXPECT() *MockSessionProvider_Expecter {
	return &MockSessionProvider_Expecter{mock: &_m.Mock}
}

// CreateScrapingSession provides a mock function for the type MockSessionProvider
func (_mock *MockSessionProvider) CreateScrapingSession(ctx context.Context) (uuid.UUID, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CreateScrapingSession")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (uuid.UUID, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) uuid.UUID); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionProvider_CreateScrapingSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateScrapingSession'
type MockSessionProvider_CreateScrapingSession_Call struct {
	*mock.Call
}

// CreateScrapingSession is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSessionProvider_Expecter) CreateScrapingSession(ctx interface{}) *MockSessionProvider_CreateScrapingSession_Call {
	return &MockSessionProvider_CreateScrapingSession_Call{Call: _e.mock.On("CreateScrapingSession", ctx)}
}

func (_c *MockSessionProvider_CreateScrapingSession_Call) Run(run func(ctx context.Context)) *MockSessionProvider_CreateScrapingSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSessionProvider_CreateScrapingSession_Call) Return(uUID uuid.UUID, err error) *MockSessionProvider_CreateScrapingSession_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockSessionProvider_CreateScrapingSession_Call) RunAndReturn(run func(ctx context.Context) (uuid.UUID, error)) *MockSessionProvider_CreateScrapingSession_Call {
	_c.Call.Return(run)
	return _c
}
