// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSkillCorpusProvider creates a new instance of MockSkillCorpusProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSkillCorpusProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSkillCorpusProvider {
	mock := &MockSkillCorpusProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSkillCorpusProvider is an autogenerated mock type for the SkillCorpusProvider type
type MockSkillCorpusProvider struct {
	mock.Mock
}

type MockSkillCorpusProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSkillCorpusProvider) EXPECT() *MockSkillCorpusProvider_Expecter {
	return &MockSkillCorpusProvider_Expecter{mock: &_m.Mock}
}

// GetActiveSkillCorpus provides a mock function for the type MockSkillCorpusProvider
func (_mock *MockSkillCorpusProvider) GetActiveSkillCorpus(ctx context.Context) (map[uuid.UUID]map[string]int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveSkillCorpus")
	}

	var r0 map[uuid.UUID]map[string]int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[uuid.UUID]map[string]int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[uuid.UUID]map[string]int); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID]map[string]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSkillCorpusProvider_GetActiveSkillCorpus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveSkillCorpus'
type MockSkillCorpusProvider_GetActiveSkillCorpus_Call struct {
	*mock.Call
}

// GetActiveSkillCorpus is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSkillCorpusProvider_Expecter) GetActiveSkillCorpus(ctx interface{}) *MockSkillCorpusProvider_GetActiveSkillCorpus_Call {
	return &MockSkillCorpusProvider_GetActiveSkillCorpus_Call{Call: _e.mock.On("GetActiveSkillCorpus", ctx)}
}

func (_c *MockSkillCorpusProvider_GetActiveSkillCorpus_Call) Run(run func(ctx context.Context)) *MockSkillCorpusProvider_GetActiveSkillCorpus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSkillCorpusProvider_GetActiveSkillCorpus_Call) Return(uUIDToStringToInt map[uuid.UUID]map[string]int, err error) *MockSkillCorpusProvider_GetActiveSkillCorpus_Call {
	_c.Call.Return(uUIDToStringToInt, err)
	return _c
}

func (_c *MockSkillCorpusProvider_GetActiveSkillCorpus_Call) RunAndReturn(run func(ctx context.Context) (map[uuid.UUID]map[string]int, error)) *MockSkillCorpusProvider_GetActiveSkillCorpus_Call {
	_c.Call.Return(run)
	return _c
}
