// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSkillsProvider creates a new instance of MockSkillsProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSkillsProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSkillsProvider {
	mock := &MockSkillsProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSkillsProvider is an autogenerated mock type for the SkillsProvider type
type MockSkillsProvider struct {
	mock.Mock
}

type MockSkillsProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSkillsProvider) EXPECT() *MockSkillsProvider_Expecter {
	return &MockSkillsProvider_Expecter{mock: &_m.Mock}
}

// SaveExtractedSkills provides a mock function for the type MockSkillsProvider
func (_mock *MockSkillsProvider) SaveExtractedSkills(ctx context.Context, sessionID uuid.UUID, professionID uuid.UUID, skills map[string]int) error {
	ret := _mock.Called(ctx, sessionID, professionID, skills)

	if len(ret) == 0 {
		panic("no return value specified for SaveExtractedSkills")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, map[string]int) error); ok {
		r0 = returnFunc(ctx, sessionID, professionID, skills)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSkillsProvider_SaveExtractedSkills_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveExtractedSkills'
type MockSkillsProvider_SaveExtractedSkills_Call struct {
	*mock.Call
}

// SaveExtractedSkills is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
//   - professionID uuid.UUID
//   - skills map[string]int
func (_e *MockSkillsProvider_Expecter) SaveExtractedSkills(ctx interface{}, sessionID interface{}, professionID interface{}, skills interface{}) *MockSkillsProvider_SaveExtractedSkills_Call {
	return &MockSkillsProvider_SaveExtractedSkills_Call{Call: _e.mock.On("SaveExtractedSkills", ctx, sessionID, professionID, skills)}
}

func (_c *MockSkillsProvider_SaveExtractedSkills_Call) Run(run func(ctx context.Context, sessionID uuid.UUID, professionID uuid.UUID, skills map[string]int)) *MockSkillsProvider_SaveExtractedSkills_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 map[string]int
		if args[3] != nil {
			arg3 = args[3].(map[string]int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSkillsProvider_SaveExtractedSkills_Call) Return(err error) *MockSkillsProvider_SaveExtractedSkills_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSkillsProvider_SaveExtractedSkills_Call) RunAndReturn(run func(ctx context.Context, sessionID uuid.UUID, professionID uuid.UUID, skills map[string]int) error) *MockSkillsProvider_SaveExtractedSkills_Call {
	_c.Call.Return(run)
	return _c
}

// SaveFormalSkills provides a mock function for the type MockSkillsProvider
func (_mock *MockSkillsProvider) SaveFormalSkills(ctx context.Context, sessionID uuid.UUID, professionID uuid.UUID, skills map[string]int) error {
	ret := _mock.Called(ctx, sessionID, professionID, skills)

	if len(ret) == 0 {
		panic("no return value specified for SaveFormalSkills")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, map[string]int) error); ok {
		r0 = returnFunc(ctx, sessionID, professionID, skills)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSkillsProvider_SaveFormalSkills_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveFormalSkills'
type MockSkillsProvider_SaveFormalSkills_Call struct {
	*mock.Call
}

// SaveFormalSkills is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
//   - professionID uuid.UUID
//   - skills map[string]int
func (_e *MockSkillsProvider_Expecter) SaveFormalSkills(ctx interface{}, sessionID interface{}, professionID interface{}, skills interface{}) *MockSkillsProvider_SaveFormalSkills_Call {
	return &MockSkillsProvider_SaveFormalSkills_Call{Call: _e.mock.On("SaveFormalSkills", ctx, sessionID, professionID, skills)}
}

func (_c *MockSkillsProvider_SaveFormalSkills_Call) Run(run func(ctx context.Context, sessionID uuid.UUID, professionID uuid.UUID, skills map[string]int)) *MockSkillsProvider_SaveFormalSkills_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 map[string]int
		if args[3] != nil {
			arg3 = args[3].(map[string]int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSkillsProvider_SaveFormalSkills_Call) Return(err error) *MockSkillsProvider_SaveFormalSkills_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSkillsProvider_SaveFormalSkills_Call) RunAndReturn(run func(ctx context.Context, sessionID uuid.UUID, professionID uuid.UUID, skills map[string]int) error) *MockSkillsProvider_SaveFormalSkills_Call {
	_c.Call.Return(run)
	return _c
}
