// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStatProvider creates a new instance of MockStatProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatProvider {
	mock := &MockStatProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStatProvider is an autogenerated mock type for the StatProvider type
type MockStatProvider struct {
	mock.Mock
}

type MockStatProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatProvider) EXPECT() *MockStatProvider_Expecter {
	return &MockStatProvider_Expecter{mock: &_m.Mock}
}

// SaveStat provides a mock function for the type MockStatProvider
func (_mock *MockStatProvider) SaveStat(ctx context.Context, sessionID uuid.UUID, professionID uuid.UUID, vacancyCount int) error {
	ret := _mock.Called(ctx, sessionID, professionID, vacancyCount)

	if len(ret) == 0 {
		panic("no return value specified for SaveStat")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int) error); ok {
		r0 = returnFunc(ctx, sessionID, professionID, vacancyCount)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStatProvider_SaveStat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveStat'
type MockStatProvider_SaveStat_Call struct {
	*mock.Call
}

// SaveStat is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
//   - professionID uuid.UUID
//   - vacancyCount int
func (_e *MockStatProvider_Expecter) SaveStat(ctx interface{}, sessionID interface{}, professionID interface{}, vacancyCount interface{}) *MockStatProvider_SaveStat_Call {
	return &MockStatProvider_SaveStat_Call{Call: _e.mock.On("SaveStat", ctx, sessionID, professionID, vacancyCount)}
}

func (_c *MockStatProvider_SaveStat_Call) Run(run func(ctx context.Context, sessionID uuid.UUID, professionID uuid.UUID, vacancyCount int)) *MockStatProvider_SaveStat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStatProvider_SaveStat_Call) Return(err error) *MockStatProvider_SaveStat_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStatProvider_SaveStat_Call) RunAndReturn(run func(ctx context.Context, sessionID uuid.UUID, professionID uuid.UUID, vacancyCount int) error) *MockStatProvider_SaveStat_Call {
	_c.Call.Return(run)
	return _c
}
