// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"psa/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSupplierPort creates a new instance of MockSupplierPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSupplierPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSupplierPort {
	mock := &MockSupplierPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSupplierPort is an autogenerated mock type for the SupplierPort type
type MockSupplierPort struct {
	mock.Mock
}

type MockSupplierPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSupplierPort) EXPECT() *MockSupplierPort_Expecter {
	return &MockSupplierPort_Expecter{mock: &_m.Mock}
}

// FetchDataProfession provides a mock function for the type MockSupplierPort
func (_mock *MockSupplierPort) FetchDataProfession(ctx context.Context, query string, area string) ([]domain.VacancyData, int, error) {
	ret := _mock.Called(ctx, query, area)

	if len(ret) == 0 {
		panic("no return value specified for FetchDataProfession")
	}

	var r0 []domain.VacancyData
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]domain.VacancyData, int, error)); ok {
		return returnFunc(ctx, query, area)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []domain.VacancyData); ok {
		r0 = returnFunc(ctx, query, area)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.VacancyData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) int); ok {
		r1 = returnFunc(ctx, query, area)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, query, area)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSupplierPort_FetchDataProfession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchDataProfession'
type MockSupplierPort_FetchDataProfession_Call struct {
	*mock.Call
}

// FetchDataProfession is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - area string
func (_e *MockSupplierPort_Expecter) FetchDataProfession(ctx interface{}, query interface{}, area interface{}) *MockSupplierPort_FetchDataProfession_Call {
	return &MockSupplierPort_FetchDataProfession_Call{Call: _e.mock.On("FetchDataProfession", ctx, query, area)}
}

func (_c *MockSupplierPort_FetchDataProfession_Call) Run(run func(ctx context.Context, query string, area string)) *MockSupplierPort_FetchDataProfession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSupplierPort_FetchDataProfession_Call) Return(vacancyDatas []domain.VacancyData, n int, err error) *MockSupplierPort_FetchDataProfession_Call {
	_c.Call.Return(vacancyDatas, n, err)
	return _c
}

func (_c *MockSupplierPort_FetchDataProfession_Call) RunAndReturn(run func(ctx context.Context, query string, area string) ([]domain.VacancyData, int, error)) *MockSupplierPort_FetchDataProfession_Call {
	_c.Call.Return(run)
	return _c
}
