INSERT INTO profession (name, vacancy_query, is_active)
VALUES ('Go Developer',
        '(go developer OR golang) NOT (full* OR php OR qa OR java OR python OR js)',
        true),
       ('System Analyst',
        '(системный аналитик OR system analyst) NOT (бизнес OR business OR программист OR full* OR devops)',
        true),
       ('1C Developer',
        'программист 1с NOT аналитик',
        true),
       ('Frontend Developer',
        'frontend NOT (full* OR php OR qa OR java OR python OR go OR qt OR администратор)',
        true),
       ('PHP Developer',
        'php developer NOT (full* OR frontend OR 1c OR vue OR react OR битрикс* OR go* OR wordpress OR bitrix* OR js OR web OR python OR +go OR фуллстек OR php/nodejs)',
        true),
       ('Android Developer',
        'android developer NOT (ios OR c++)',
        true),
       ('QA Automation',
        '(aqa OR qa automation) NOT (embedded OR full*)',
        true),
       ('QA Engineer',
        'qa NOT (aqa OR automation OR auto* OR full*)',
        true),
       ('Business Analyst',
        '(бизнес аналитик OR business analyst) NOT (менеджер OR консультант OR data OR процессов OR финансовый OR методолог OR project OR системный OR system OR кредитный)',
        true),
       ('C# Developer',
        '(c# OR .net) NOT (unity OR full* OR qa OR sdet OR c++ OR авто* OR java OR go OR python)',
        true),
       ('C++ Developer',
        'c++ developer NOT (manager OR delphi OR embedded OR unreal OR микроконтроллер OR c# OR .net OR go OR python OR rust* OR java* OR android OR робот* OR встроен* OR авто*)',
        true),
       ('Data Analyst',
        '("аналитик данных" OR "data analyst") NOT (1с OR бизнес* OR scientist* OR product* OR продуктовый* OR (data engineer) OR dwh)',
        true),
       ('Data Engineer',
        'data engineer NOT (ml OR scie* OR analyst OR sec* OR dev* OR dwh OR auto*)',
        true),
       ('DBA',
        'dba NOT (data OR devops OR системный OR менеджер)',
        true),
       ('DevOps',
        'devops NOT (sre OR админ* OR иб OR dwh OR ml* OR data OR системный OR архитектор OR разработчик)',
        true),
       ('Embedded Developer',
        '(embedded developer OR микроконтроллер) NOT aqa',
        true),
       ('Flutter Developer',
        'flutter NOT (java OR react)',
        true),
       ('iOS Developer',
        '(ios developer OR swift) NOT (android OR менеджер OR qa OR react)',
        true),
       ('Java Developer',
        'java NOT (kotlin OR go OR python OR c# OR c++ OR full* OR js OR aqa OR qa OR auto* OR sdet OR тест* OR авто* OR flutter OR ruby OR ml*)',
        true),
       ('Kotlin Developer',
        'kotlin NOT (java OR qa OR devops OR aqa OR android OR тест* OR ios OR flutter)',
        true),
       ('ML Engineer',
        '(ml engineer OR machine learning OR машин* обучение OR ml*) NOT (data OR scientist OR full* OR go* OR c++* OR java OR метод* OR аналитик OR менеджер OR разработчик OR mlm OR алгоритм* OR азс OR sre OR рук* OR пис* OR сопров* OR разраб* OR диз*)',
        true),
       ('Node.js Developer',
        'node* NOT (full* OR go OR python OR java OR c# OR next* OR front* OR php* OR react OR rust)',
        true),
       ('Product Analyst',
        '("продуктовый аналитик" OR "product analyst") NOT (менеджер OR систем* OR system OR бизнес* OR data OR дата OR full* OR рук* OR отрасл* OR проектиров* OR данн*)',
        true),
       ('Python Developer',
        'python developer NOT (ml* OR go* OR full* OR front* OR c++ OR java OR c# OR js OR аналит* OR qa OR aqa OR php OR devops OR тест* OR +go OR typescript OR data*)',
        true),
       ('React Developer',
        'react developer NOT (php OR python OR vue OR angular OR full*)',
        true),
       ('Rust Developer',
        'rust developer NOT (full* OR node*)',
        true),
       ('Scala Developer',
        'scala NOT data',
        true),
       ('Data Scientist',
        '(data science OR data scientist) NOT ((data engineer) OR бизнес* OR мед* OR mlops OR full* OR manager OR analytic* OR дата*)',
        true),
       ('SRE Engineer',
        '(sre OR !"site reliability engineer") NOT devops',
        true),
       ('Unity Developer',
        '"unity developer"',
        true),
       ('Unreal Engine Developer',
        'unreal engine developer NOT unity',
        true),
       ('Vue Developer',
        '"vue developer" NOT (php OR python OR react)',
        true),
       ('System Administrator',
        'системный администратор NOT (devops OR sre OR скс OR сет* OR комп* OR аналит* OR поддерж* OR программист OR проектов OR техник)',
        true),
       ('Information Security',
        '(специалист иб OR информационная безопасность) NOT (директор OR аналитик OR менеджер OR пресейл OR go* OR контролер)',
        true),
       ('1C Analyst',
        'аналитик 1с NOT (бизнес OR системный OR разработчик OR технич* OR продуктовый)',
        true)
ON CONFLICT (name) DO NOTHING;