DROP TABLE IF EXISTS stat_daily CASCADE;
DROP TABLE IF EXISTS stat CASCADE;
DROP TABLE IF EXISTS skill_extracted CASCADE;
DROP TABLE IF EXISTS skill_formal CASCADE;
DROP TABLE IF EXISTS refresh_tokens CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS scraping CASCADE;
DROP TABLE IF EXISTS profession CASCADE;