INSERT INTO profession (name, vacancy_query, is_active)
VALUES ('Go Developer',
        'go developer OR golang',
        true),
       ('System Analyst',
        '!"Системный аналитик" OR !"system analyst" NOT ("Бизнес аналитик" OR "business analyst" OR business OR бизнес)',
        true),
       ('1С Developer',
        'программист 1с',
        true),
       ('Frontend Developer',
        'front OR frontend',
        true),
       ('PHP Developer',
        'php developer not fullstack not frontend not 1c not vue not react not битрикс',
        true),
       ('Android Developer',
        'android developer',
        true),
       ('AQA Engineer',
        'aqa',
        true),
       ('QA Engineer',
        'qa not aqa not automation',
        true),
       ('Business Analyst',
        '"бизнес аналитик" or "business analyst" not системный not system',
        true),
       ('C# Developer',
        'c# not unity',
        true),
       ('C++ Developer',
        'c++ developer not embedded not (unreal engine) not микроконтроллер',
        true),
       ('Data Analyst',
        '"аналитик данных" or "data analyst"',
        true),
       ('Data Engineer',
        'data engineer not ml not scientist',
        true),
       ('DBA',
        'dba not data',
        true),
       ('DevOps',
        'devops not sre not (системный администратор)',
        true),
       ('Embedded Developer',
        'embedded developer',
        true),
       ('Flutter Developer',
        'flutter',
        true),
       ('iOS Developer',
        'ios developer',
        true),
       ('Java Developer',
        'java not kotlin',
        true),
       ('Kotlin Developer',
        'kotlin not java not qa not devops not aqa not android',
        true),
       ('ML Engineer',
        'ml engineer not data not scientist',
        true),
       ('Node.js Developer',
        'node.js not fullstack',
        true),
       ('Product Analyst',
        '"продуктовый аналитик" or "product analyst" not системный not system not бизнес',
        true),
       ('Product Manager',
        'it product manager or продакт not продаж not project not маркетинг',
        true),
       ('Project Manager',
        'it project manager or (it менеджер проектов) not продаж',
        true),
       ('Python Developer',
        'python developer not ml',
        true),
       ('React Developer',
        '"react developer" not php not python not vue not angular',
        true),
       ('Rust Developer',
        'rust developer',
        true),
       ('Scala Developer',
        'scala not data',
        true),
       ('Data Scientist',
        'scientist not ml not (data engineer)',
        true),
       ('SRE Engineer',
        'sre not devops',
        true),
       ('Unity Developer',
        '"unity developer"',
        true),
       ('Unreal Engine Developer',
        'unreal engine developer not unity',
        true),
       ('Vue Developer',
        '"vue developer" not php not python not react',
        true),
       ('System Administrator',
        'системный администратор not devops not sre',
        true)
ON CONFLICT (name) DO NOTHING;