// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"psa/internal/domain"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockJWTProvider creates a new instance of MockJWTProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJWTProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJWTProvider {
	mock := &MockJWTProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJWTProvider is an autogenerated mock type for the JWTProvider type
type MockJWTProvider struct {
	mock.Mock
}

type MockJWTProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJWTProvider) EXPECT() *MockJWTProvider_Expecter {
	return &MockJWTProvider_Expecter{mock: &_m.Mock}
}

// GenerateAccessToken provides a mock function for the type MockJWTProvider
func (_mock *MockJWTProvider) GenerateAccessToken(ctx context.Context, userID uuid.UUID, role string) (string, error) {
	ret := _mock.Called(ctx, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (string, error)); ok {
		return returnFunc(ctx, userID, role)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) string); ok {
		r0 = returnFunc(ctx, userID, role)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, userID, role)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJWTProvider_GenerateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAccessToken'
type MockJWTProvider_GenerateAccessToken_Call struct {
	*mock.Call
}

// GenerateAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - role string
func (_e *MockJWTProvider_Expecter) GenerateAccessToken(ctx interface{}, userID interface{}, role interface{}) *MockJWTProvider_GenerateAccessToken_Call {
	return &MockJWTProvider_GenerateAccessToken_Call{Call: _e.mock.On("GenerateAccessToken", ctx, userID, role)}
}

func (_c *MockJWTProvider_GenerateAccessToken_Call) Run(run func(ctx context.Context, userID uuid.UUID, role string)) *MockJWTProvider_GenerateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJWTProvider_GenerateAccessToken_Call) Return(s string, err error) *MockJWTProvider_GenerateAccessToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockJWTProvider_GenerateAccessToken_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, role string) (string, error)) *MockJWTProvider_GenerateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateRefreshToken provides a mock function for the type MockJWTProvider
func (_mock *MockJWTProvider) GenerateRefreshToken(ctx context.Context, userID uuid.UUID) (string, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRefreshToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (string, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) string); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJWTProvider_GenerateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRefreshToken'
type MockJWTProvider_GenerateRefreshToken_Call struct {
	*mock.Call
}

// GenerateRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockJWTProvider_Expecter) GenerateRefreshToken(ctx interface{}, userID interface{}) *MockJWTProvider_GenerateRefreshToken_Call {
	return &MockJWTProvider_GenerateRefreshToken_Call{Call: _e.mock.On("GenerateRefreshToken", ctx, userID)}
}

func (_c *MockJWTProvider_GenerateRefreshToken_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockJWTProvider_GenerateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJWTProvider_GenerateRefreshToken_Call) Return(s string, err error) *MockJWTProvider_GenerateRefreshToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockJWTProvider_GenerateRefreshToken_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (string, error)) *MockJWTProvider_GenerateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// HashToken provides a mock function for the type MockJWTProvider
func (_mock *MockJWTProvider) HashToken(token string) string {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for HashToken")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(token)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockJWTProvider_HashToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashToken'
type MockJWTProvider_HashToken_Call struct {
	*mock.Call
}

// HashToken is a helper method to define mock.On call
//   - token string
func (_e *MockJWTProvider_Expecter) HashToken(token interface{}) *MockJWTProvider_HashToken_Call {
	return &MockJWTProvider_HashToken_Call{Call: _e.mock.On("HashToken", token)}
}

func (_c *MockJWTProvider_HashToken_Call) Run(run func(token string)) *MockJWTProvider_HashToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJWTProvider_HashToken_Call) Return(s string) *MockJWTProvider_HashToken_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockJWTProvider_HashToken_Call) RunAndReturn(run func(token string) string) *MockJWTProvider_HashToken_Call {
	_c.Call.Return(run)
	return _c
}

// ParseToken provides a mock function for the type MockJWTProvider
func (_mock *MockJWTProvider) ParseToken(ctx context.Context, token string) (*domain.TokenClaims, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ParseToken")
	}

	var r0 *domain.TokenClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.TokenClaims, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.TokenClaims); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TokenClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJWTProvider_ParseToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseToken'
type MockJWTProvider_ParseToken_Call struct {
	*mock.Call
}

// ParseToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockJWTProvider_Expecter) ParseToken(ctx interface{}, token interface{}) *MockJWTProvider_ParseToken_Call {
	return &MockJWTProvider_ParseToken_Call{Call: _e.mock.On("ParseToken", ctx, token)}
}

func (_c *MockJWTProvider_ParseToken_Call) Run(run func(ctx context.Context, token string)) *MockJWTProvider_ParseToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJWTProvider_ParseToken_Call) Return(tokenClaims *domain.TokenClaims, err error) *MockJWTProvider_ParseToken_Call {
	_c.Call.Return(tokenClaims, err)
	return _c
}

func (_c *MockJWTProvider_ParseToken_Call) RunAndReturn(run func(ctx context.Context, token string) (*domain.TokenClaims, error)) *MockJWTProvider_ParseToken_Call {
	_c.Call.Return(run)
	return _c
}
