// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"psa/internal/domain"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRefreshTokenProvider creates a new instance of MockRefreshTokenProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRefreshTokenProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRefreshTokenProvider {
	mock := &MockRefreshTokenProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRefreshTokenProvider is an autogenerated mock type for the RefreshTokenProvider type
type MockRefreshTokenProvider struct {
	mock.Mock
}

type MockRefreshTokenProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRefreshTokenProvider) EXPECT() *MockRefreshTokenProvider_Expecter {
	return &MockRefreshTokenProvider_Expecter{mock: &_m.Mock}
}

// CreateRefreshToken provides a mock function for the type MockRefreshTokenProvider
func (_mock *MockRefreshTokenProvider) CreateRefreshToken(ctx context.Context, token *domain.RefreshToken) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for CreateRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.RefreshToken) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRefreshTokenProvider_CreateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRefreshToken'
type MockRefreshTokenProvider_CreateRefreshToken_Call struct {
	*mock.Call
}

// CreateRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token *domain.RefreshToken
func (_e *MockRefreshTokenProvider_Expecter) CreateRefreshToken(ctx interface{}, token interface{}) *MockRefreshTokenProvider_CreateRefreshToken_Call {
	return &MockRefreshTokenProvider_CreateRefreshToken_Call{Call: _e.mock.On("CreateRefreshToken", ctx, token)}
}

func (_c *MockRefreshTokenProvider_CreateRefreshToken_Call) Run(run func(ctx context.Context, token *domain.RefreshToken)) *MockRefreshTokenProvider_CreateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.RefreshToken
		if args[1] != nil {
			arg1 = args[1].(*domain.RefreshToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRefreshTokenProvider_CreateRefreshToken_Call) Return(err error) *MockRefreshTokenProvider_CreateRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRefreshTokenProvider_CreateRefreshToken_Call) RunAndReturn(run func(ctx context.Context, token *domain.RefreshToken) error) *MockRefreshTokenProvider_CreateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpiredRefreshTokens provides a mock function for the type MockRefreshTokenProvider
func (_mock *MockRefreshTokenProvider) DeleteExpiredRefreshTokens(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpiredRefreshTokens")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRefreshTokenProvider_DeleteExpiredRefreshTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpiredRefreshTokens'
type MockRefreshTokenProvider_DeleteExpiredRefreshTokens_Call struct {
	*mock.Call
}

// DeleteExpiredRefreshTokens is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRefreshTokenProvider_Expecter) DeleteExpiredRefreshTokens(ctx interface{}) *MockRefreshTokenProvider_DeleteExpiredRefreshTokens_Call {
	return &MockRefreshTokenProvider_DeleteExpiredRefreshTokens_Call{Call: _e.mock.On("DeleteExpiredRefreshTokens", ctx)}
}

func (_c *MockRefreshTokenProvider_DeleteExpiredRefreshTokens_Call) Run(run func(ctx context.Context)) *MockRefreshTokenProvider_DeleteExpiredRefreshTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRefreshTokenProvider_DeleteExpiredRefreshTokens_Call) Return(err error) *MockRefreshTokenProvider_DeleteExpiredRefreshTokens_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRefreshTokenProvider_DeleteExpiredRefreshTokens_Call) RunAndReturn(run func(ctx context.Context) error) *MockRefreshTokenProvider_DeleteExpiredRefreshTokens_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRefreshToken provides a mock function for the type MockRefreshTokenProvider
func (_mock *MockRefreshTokenProvider) DeleteRefreshToken(ctx context.Context, userID uuid.UUID, hashedToken string) error {
	ret := _mock.Called(ctx, userID, hashedToken)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRefreshToken")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, userID, hashedToken)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRefreshTokenProvider_DeleteRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRefreshToken'
type MockRefreshTokenProvider_DeleteRefreshToken_Call struct {
	*mock.Call
}

// DeleteRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - hashedToken string
func (_e *MockRefreshTokenProvider_Expecter) DeleteRefreshToken(ctx interface{}, userID interface{}, hashedToken interface{}) *MockRefreshTokenProvider_DeleteRefreshToken_Call {
	return &MockRefreshTokenProvider_DeleteRefreshToken_Call{Call: _e.mock.On("DeleteRefreshToken", ctx, userID, hashedToken)}
}

func (_c *MockRefreshTokenProvider_DeleteRefreshToken_Call) Run(run func(ctx context.Context, userID uuid.UUID, hashedToken string)) *MockRefreshTokenProvider_DeleteRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRefreshTokenProvider_DeleteRefreshToken_Call) Return(err error) *MockRefreshTokenProvider_DeleteRefreshToken_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRefreshTokenProvider_DeleteRefreshToken_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, hashedToken string) error) *MockRefreshTokenProvider_DeleteRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefreshToken provides a mock function for the type MockRefreshTokenProvider
func (_mock *MockRefreshTokenProvider) GetRefreshToken(ctx context.Context, userID uuid.UUID, hashedToken string) (*domain.RefreshToken, error) {
	ret := _mock.Called(ctx, userID, hashedToken)

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshToken")
	}

	var r0 *domain.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*domain.RefreshToken, error)); ok {
		return returnFunc(ctx, userID, hashedToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *domain.RefreshToken); ok {
		r0 = returnFunc(ctx, userID, hashedToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RefreshToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, userID, hashedToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRefreshTokenProvider_GetRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefreshToken'
type MockRefreshTokenProvider_GetRefreshToken_Call struct {
	*mock.Call
}

// GetRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - hashedToken string
func (_e *MockRefreshTokenProvider_Expecter) GetRefreshToken(ctx interface{}, userID interface{}, hashedToken interface{}) *MockRefreshTokenProvider_GetRefreshToken_Call {
	return &MockRefreshTokenProvider_GetRefreshToken_Call{Call: _e.mock.On("GetRefreshToken", ctx, userID, hashedToken)}
}

func (_c *MockRefreshTokenProvider_GetRefreshToken_Call) Run(run func(ctx context.Context, userID uuid.UUID, hashedToken string)) *MockRefreshTokenProvider_GetRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRefreshTokenProvider_GetRefreshToken_Call) Return(refreshToken *domain.RefreshToken, err error) *MockRefreshTokenProvider_GetRefreshToken_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *MockRefreshTokenProvider_GetRefreshToken_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, hashedToken string) (*domain.RefreshToken, error)) *MockRefreshTokenProvider_GetRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}
