// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"psa/internal/domain"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProfessionAdminAccesser creates a new instance of MockProfessionAdminAccesser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfessionAdminAccesser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfessionAdminAccesser {
	mock := &MockProfessionAdminAccesser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProfessionAdminAccesser is an autogenerated mock type for the ProfessionAdminAccesser type
type MockProfessionAdminAccesser struct {
	mock.Mock
}

type MockProfessionAdminAccesser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProfessionAdminAccesser) EXPECT() *MockProfessionAdminAccesser_Expecter {
	return &MockProfessionAdminAccesser_Expecter{mock: &_m.Mock}
}

// AllProfessions provides a mock function for the type MockProfessionAdminAccesser
func (_mock *MockProfessionAdminAccesser) AllProfessions(ctx context.Context) ([]domain.Profession, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AllProfessions")
	}

	var r0 []domain.Profession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.Profession, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Profession); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Profession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfessionAdminAccesser_AllProfessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllProfessions'
type MockProfessionAdminAccesser_AllProfessions_Call struct {
	*mock.Call
}

// AllProfessions is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProfessionAdminAccesser_Expecter) AllProfessions(ctx interface{}) *MockProfessionAdminAccesser_AllProfessions_Call {
	return &MockProfessionAdminAccesser_AllProfessions_Call{Call: _e.mock.On("AllProfessions", ctx)}
}

func (_c *MockProfessionAdminAccesser_AllProfessions_Call) Run(run func(ctx context.Context)) *MockProfessionAdminAccesser_AllProfessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProfessionAdminAccesser_AllProfessions_Call) Return(professions []domain.Profession, err error) *MockProfessionAdminAccesser_AllProfessions_Call {
	_c.Call.Return(professions, err)
	return _c
}

func (_c *MockProfessionAdminAccesser_AllProfessions_Call) RunAndReturn(run func(ctx context.Context) ([]domain.Profession, error)) *MockProfessionAdminAccesser_AllProfessions_Call {
	_c.Call.Return(run)
	return _c
}

// ChangeProfession provides a mock function for the type MockProfessionAdminAccesser
func (_mock *MockProfessionAdminAccesser) ChangeProfession(ctx context.Context, profession domain.Profession) error {
	ret := _mock.Called(ctx, profession)

	if len(ret) == 0 {
		panic("no return value specified for ChangeProfession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Profession) error); ok {
		r0 = returnFunc(ctx, profession)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProfessionAdminAccesser_ChangeProfession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeProfession'
type MockProfessionAdminAccesser_ChangeProfession_Call struct {
	*mock.Call
}

// ChangeProfession is a helper method to define mock.On call
//   - ctx context.Context
//   - profession domain.Profession
func (_e *MockProfessionAdminAccesser_Expecter) ChangeProfession(ctx interface{}, profession interface{}) *MockProfessionAdminAccesser_ChangeProfession_Call {
	return &MockProfessionAdminAccesser_ChangeProfession_Call{Call: _e.mock.On("ChangeProfession", ctx, profession)}
}

func (_c *MockProfessionAdminAccesser_ChangeProfession_Call) Run(run func(ctx context.Context, profession domain.Profession)) *MockProfessionAdminAccesser_ChangeProfession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Profession
		if args[1] != nil {
			arg1 = args[1].(domain.Profession)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfessionAdminAccesser_ChangeProfession_Call) Return(err error) *MockProfessionAdminAccesser_ChangeProfession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProfessionAdminAccesser_ChangeProfession_Call) RunAndReturn(run func(ctx context.Context, profession domain.Profession) error) *MockProfessionAdminAccesser_ChangeProfession_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProfession provides a mock function for the type MockProfessionAdminAccesser
func (_mock *MockProfessionAdminAccesser) CreateProfession(ctx context.Context, profession domain.Profession) (uuid.UUID, error) {
	ret := _mock.Called(ctx, profession)

	if len(ret) == 0 {
		panic("no return value specified for CreateProfession")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Profession) (uuid.UUID, error)); ok {
		return returnFunc(ctx, profession)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Profession) uuid.UUID); ok {
		r0 = returnFunc(ctx, profession)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Profession) error); ok {
		r1 = returnFunc(ctx, profession)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfessionAdminAccesser_CreateProfession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProfession'
type MockProfessionAdminAccesser_CreateProfession_Call struct {
	*mock.Call
}

// CreateProfession is a helper method to define mock.On call
//   - ctx context.Context
//   - profession domain.Profession
func (_e *MockProfessionAdminAccesser_Expecter) CreateProfession(ctx interface{}, profession interface{}) *MockProfessionAdminAccesser_CreateProfession_Call {
	return &MockProfessionAdminAccesser_CreateProfession_Call{Call: _e.mock.On("CreateProfession", ctx, profession)}
}

func (_c *MockProfessionAdminAccesser_CreateProfession_Call) Run(run func(ctx context.Context, profession domain.Profession)) *MockProfessionAdminAccesser_CreateProfession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Profession
		if args[1] != nil {
			arg1 = args[1].(domain.Profession)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfessionAdminAccesser_CreateProfession_Call) Return(uUID uuid.UUID, err error) *MockProfessionAdminAccesser_CreateProfession_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockProfessionAdminAccesser_CreateProfession_Call) RunAndReturn(run func(ctx context.Context, profession domain.Profession) (uuid.UUID, error)) *MockProfessionAdminAccesser_CreateProfession_Call {
	_c.Call.Return(run)
	return _c
}
