// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockScrapingProvider creates a new instance of MockScrapingProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScrapingProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScrapingProvider {
	mock := &MockScrapingProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockScrapingProvider is an autogenerated mock type for the ScrapingProvider type
type MockScrapingProvider struct {
	mock.Mock
}

type MockScrapingProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScrapingProvider) EXPECT() *MockScrapingProvider_Expecter {
	return &MockScrapingProvider_Expecter{mock: &_m.Mock}
}

// ProcessActiveProfessionsArchive provides a mock function for the type MockScrapingProvider
func (_mock *MockScrapingProvider) ProcessActiveProfessionsArchive(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ProcessActiveProfessionsArchive")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockScrapingProvider_ProcessActiveProfessionsArchive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessActiveProfessionsArchive'
type MockScrapingProvider_ProcessActiveProfessionsArchive_Call struct {
	*mock.Call
}

// ProcessActiveProfessionsArchive is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockScrapingProvider_Expecter) ProcessActiveProfessionsArchive(ctx interface{}) *MockScrapingProvider_ProcessActiveProfessionsArchive_Call {
	return &MockScrapingProvider_ProcessActiveProfessionsArchive_Call{Call: _e.mock.On("ProcessActiveProfessionsArchive", ctx)}
}

func (_c *MockScrapingProvider_ProcessActiveProfessionsArchive_Call) Run(run func(ctx context.Context)) *MockScrapingProvider_ProcessActiveProfessionsArchive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockScrapingProvider_ProcessActiveProfessionsArchive_Call) Return(err error) *MockScrapingProvider_ProcessActiveProfessionsArchive_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockScrapingProvider_ProcessActiveProfessionsArchive_Call) RunAndReturn(run func(ctx context.Context) error) *MockScrapingProvider_ProcessActiveProfessionsArchive_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessActiveProfessionsDaily provides a mock function for the type MockScrapingProvider
func (_mock *MockScrapingProvider) ProcessActiveProfessionsDaily(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ProcessActiveProfessionsDaily")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockScrapingProvider_ProcessActiveProfessionsDaily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessActiveProfessionsDaily'
type MockScrapingProvider_ProcessActiveProfessionsDaily_Call struct {
	*mock.Call
}

// ProcessActiveProfessionsDaily is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockScrapingProvider_Expecter) ProcessActiveProfessionsDaily(ctx interface{}) *MockScrapingProvider_ProcessActiveProfessionsDaily_Call {
	return &MockScrapingProvider_ProcessActiveProfessionsDaily_Call{Call: _e.mock.On("ProcessActiveProfessionsDaily", ctx)}
}

func (_c *MockScrapingProvider_ProcessActiveProfessionsDaily_Call) Run(run func(ctx context.Context)) *MockScrapingProvider_ProcessActiveProfessionsDaily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockScrapingProvider_ProcessActiveProfessionsDaily_Call) Return(err error) *MockScrapingProvider_ProcessActiveProfessionsDaily_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockScrapingProvider_ProcessActiveProfessionsDaily_Call) RunAndReturn(run func(ctx context.Context) error) *MockScrapingProvider_ProcessActiveProfessionsDaily_Call {
	_c.Call.Return(run)
	return _c
}
